apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: test
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: kost2191/sopo:ubuntu
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo privet sopo
          restartPolicy: OnFailure
