apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: test
spec:
  containers:
    - name: webserver
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "64Mi"
          cpu: "500m"
